# Module settings
yandex_maps.settings:
  type: config_object
  label: 'Database logging settings'
  mapping:
    api_key:
      type: string
      label: 'API key'
    presets_file_path:
      type: string
      label: 'Presets file path'
    objects_default_preset:
      type: string
      label: 'Objects default preset'
    debug_mode:
      type: boolean
      label: 'Yandex.Maps API debug mode'

# Widget settings
field.widget.settings.geofield_yandex_map:
  type: mapping
  label: 'Yandex Map widget settings'
  mapping:
    map_type:
      type: string
      label: 'Map type'
    map_center:
      type: string
      label: 'Map center'
    map_zoom:
      type: integer
      label: 'Map zoom level'
    map_auto_centering:
      type: boolean
      label: 'Auto centering map'
    map_auto_zooming:
      type: boolean
      label: 'Auto zooming map'
    map_controls:
      type: string
      label: 'Map controls'
    map_object_types:
      type: sequence
      label: 'Supported object types'
      sequence:
        type: string
        label: 'Object type'
    map_selected_control:
      type: string
      label: 'Default selected control'
    map_object_preset:
      type: string
      label: 'Map objects preset name'

# Formatter settings
field.formatter.settings.geofield_yandex_map:
  type: mapping
  label: 'Yandex Map formatter settings'
  mapping:
    map_type:
      type: string
      label: 'Map type'
    map_center:
      type: string
      label: 'Map center'
    map_auto_centering:
      type: boolean
      label: 'Auto centering map'
    map_zoom:
      type: integer
      label: 'Map zoom level'
    map_controls:
      type: string
      label: 'Map controls'
    map_behaviors:
      type: string
      label: 'Map behaviors'
    map_object_preset:
      type: string
      label: 'Map objects preset name'
    map_object_hint_content:
      type: string
      label: 'Map objects hint content'
    map_object_balloon_content:
      type: string
      label: 'Map objects balloon content'
    map_hide_empty:
      type: boolean
      label: 'Hide empty map'
